# Generated by Django 3.0.7 on 2020-06-07 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='haliyahewa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mkoa', models.CharField(max_length=200)),
                ('mvua', models.CharField(max_length=10)),
                ('nyuzi', models.CharField(max_length=10)),
            ],
        ),
    ]
